from sd_bmab.detectors.face import UltralyticsFaceDetector8s
from sd_bmab.detectors.face import UltralyticsFaceDetector8nv2
from sd_bmab.detectors.face import UltralyticsFaceDetector8n
from sd_bmab.detectors.face import UltralyticsFaceDetector8m
from sd_bmab.detectors.person import UltralyticsPersonDetector8m
from sd_bmab.detectors.person import UltralyticsPersonDetector8n
from sd_bmab.detectors.person import UltralyticsPersonDetector8s
from sd_bmab.detectors.hand import UltralyticsHandDetector8s
from sd_bmab.detectors.hand import UltralyticsHandDetector8n
from sd_bmab.detectors.detector import list_face_detectors, list_hand_detectors, list_person_detectors, get_detector


